name: Build and Deploy to S3

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 14

    - name: Before Install
      run: ls

    - name: Install Dependencies
      run: npm install

    - name: After Install
      run: ls

    - name: Build React App
      run: npm run build

    - name: Share artifact inside workflow
      uses: actions/upload-artifact@v1
      with:
       name: successful-build
       path: build

    - name: After build
      run: | 
        ls
        ls build
    
    - name: Working Directory
      run : pwd

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Get artifact
      uses: actions/download-artifact@v1
      with:
        name: build


    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Replace with your AWS region
        
    - name: List Objects
      run: ls

    - name: List Objects
      run: |
       pwd
       ls
      working-directory: build

    - name: List Objects
      run: aws s3 ls s3://test-bucket-4343434
    

    - name: Deploy to S3
      run: aws s3 sync . s3://test-bucket-4343434
      working-directory: build